feat(model): add new column to CloudStorageFilesModel
netless-io/flat-server pull request #245
Opened 2021-03-10 06:23 UTC by Cheerego7

2021-03-10 06:39 UTC, BlackHole1 requested changes

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/dao/Type.ts
> +import { CloudStorageConfigModel } from "../model/cloudStorage/CloudStorageConfig";
文件名应该是: `CloudStorageConfigs`

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/dao/Type.ts
> +    | CloudStorageConfigModel;
`CloudStorageConfigModel` => `CloudStorageConfigsModel`

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/dao/Type.ts
> +import { CloudStorageConfigModel } from "../model/cloudStorage/CloudStorageConfig";
`CloudStorageConfigModel` => `CloudStorageConfigsModel`

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/dao/index.ts
> +import { CloudStorageConfigModel } from "../model/cloudStorage/CloudStorageConfig";
`CloudStorageConfigModel` => `CloudStorageConfigsModel`

`CloudStorageConfig` => `CloudStorageConfigs`

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/dao/index.ts
> +    DAO<CloudStorageConfigModel>
`CloudStorageConfigModel` => `CloudStorageConfigsModel`

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageConfig.ts
> +    name: "cloud_storage_config",
`cloud_storage_config` => `cloud_storage_configs`

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageConfig.ts
> +export class CloudStorageConfigModel extends Content {
CloudStorageConfigsModel

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageConfig.ts
> +    @Index("cloud_storage_config_user_uuid_uindex", {
cloud_storage_configs_user_uuid_uindex

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        length: 128,
我们的文件名最长是128是么，文件后缀包含在内么

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        comment: "oss cdn url",
file url in oss cdn

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        type: "json",
我们使用 json 格式时，是为了存储转换结果，那么转换结果是一定不会进行更新是么，只会存在: 增 / 删 / 查 的动作是么？

如果是这样的话，这里需要在 `comment` 描述下

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +    is_converted: boolean;
这里两个状态够么，转换中的状态是不需要进行记录的是么

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        length: 256,
256 长度是经过了验证么，task_token 是否一定在 256 长度内

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        length: 40,
缺失 comment

2021-03-10 06:39 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        length: 256,
缺失 comment

2021-03-10 06:39 UTC, BlackHole1 commented on package.json
> +    "fastify-multipart": "^4.0.0",
此 PR 并没有使用到 fastify-multipart，这个应该从本次 PR 里移除

2021-03-10 06:49 UTC, Cheerego7 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +    is_converted: boolean;
转换过程前端去查询就足够，后端只查结果

2021-03-10 06:50 UTC, Cheerego7 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        length: 256,
嗯，我当时查看正在使用的task_token有203左右

2021-03-10 06:54 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        length: 128,
好的

2021-03-10 06:54 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +    is_converted: boolean;
那如果转换失败了，会怎么样

2021-03-10 06:55 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        length: 256,
多试几次的话呢

2021-03-10 08:00 UTC, hyrious commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        length: 256,
@BlackHole1 可以自己用这个项目尝试 https://github.com/netless-io/netless-token 里面的 uuid 都是 v1 的

2021-03-10 08:41 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        length: 256,
好的

2021-03-11 01:59 UTC, BlackHole1 requested changes

2021-03-11 01:59 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/Constants.ts
> +export enum ConvertStep {
FileConvertStep

2021-03-11 01:59 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/Constants.ts
> +    Failed = "failed",
value 的 首字母大写

2021-03-11 01:59 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        comment: "convert result or null",
所有的字段都是不允许为 null 的，这里的 注释是有问题的，可以改成: file convert result info

然后默认值设置为: "{}"

2021-03-11 01:59 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        comment: "convert result or null",
这个 字段是json类型，而名字起为: `file_urls` 不太符合直觉。直接改成: `convert_result` 会不会更直观

2021-03-11 02:20 UTC, BlackHole1 commented on src/v1/model/cloudStorage/CloudStorageFiles.ts
> +        comment: "convert result or null",
那需要看下，mysql支不支持类型 json，存储的是 数组

2021-03-11 06:09 UTC, BlackHole1 approved these changes

2021-03-11 06:09 UTC, merged