feat: add aliyun STS Token & task Token
netless-io/flat-server pull request #247
Opened 2021-03-12 09:43 UTC by Cheerego7

2021-03-12 09:52 UTC, BlackHole1 requested changes
ALIYUN => AlibabaCloud

2021-03-12 09:52 UTC, BlackHole1 commented on src/utils/NetlessToken.ts
> +const taskToken = createToken<RoomTokenTags>(TokenPrefix.TASK);
这里我记得是 TaskTokenTags

2021-03-12 09:52 UTC, BlackHole1 commented on src/v1/utils/request/aliyun/Aliyun.ts
> +    accessKeySecret: process.env.OSS_ACCESS_KEY_SECRET,
上面已经定义了常量，这里也应该使用常量

2021-03-12 09:52 UTC, BlackHole1 commented on src/v1/utils/request/aliyun/Aliyun.ts
> +        "flat-desktop", // session name
这几个常量，也做成 env

2021-03-12 09:52 UTC, BlackHole1 commented on typings/globals.d.ts
> +        ALIYUN_OSS_ROLE_ARN: string;
.github/workflows/main.yaml 也需要添加

2021-03-12 10:15 UTC, Cheerego7 commented on src/utils/NetlessToken.ts
> +const taskToken = createToken<RoomTokenTags>(TokenPrefix.TASK);
TaskTokenTags类型和RoomTokenTags一样

2021-03-15 10:02 UTC, BlackHole1 requested changes

2021-03-15 10:02 UTC, BlackHole1 commented on package.json
> +    "@types/ali-oss": "^6.0.7",
这个不应该在 "dependencies" 里

2021-03-15 10:02 UTC, BlackHole1 commented on src/Constants.ts
> +    ALIBABA_CLOUD_OSS_ACCESS_KEY: process.env.ALIBABA_CLOUD_OSS_ACCESS_KEY,
这里的 ”ALIBABA_CLOUD“ 可以移除了

2021-03-15 10:02 UTC, BlackHole1 commented on src/utils/NetlessToken.ts
> +        role: TokenRole.Reader,
这个是确定是 Reader   role么

2021-03-15 10:02 UTC, BlackHole1 commented on src/v1/utils/request/aliyun/Aliyun.ts
> +    const { credentials } = await sts.assumeRole(
可以把这里函数的文档地址附上，方便后期维护

2021-03-15 10:06 UTC, Cheerego7 commented on src/utils/NetlessToken.ts
> +        role: TokenRole.Reader,
是的

2021-03-15 10:50 UTC, BlackHole1 approved these changes

2021-03-15 10:50 UTC, merged