feat: add upload start api
netless-io/flat-server pull request #253
Opened 2021-03-17 02:54 UTC by Cheerego7

2021-03-17 09:49 UTC, BlackHole1 requested changes

2021-03-17 09:49 UTC, BlackHole1 commented on src/ErrorCode.ts
> +    ConvertFailed, // convert task is failed
这三个常量在本次 PR 里并没有使用到，先删除吧。等到下次 PR 用到时，再进行添加

2021-03-17 09:49 UTC, BlackHole1 commented on src/ErrorCode.ts
> +    NotEnoughTotalUsage = 800000, // not enough TotalUsage
因为上面的三个变量在本次 PR 里已经删除，所以这里应该修改为: 700000

2021-03-17 09:49 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +import { ErrorCode } from "ErrorCode";
路径引用错误

2021-03-17 09:49 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +    const config = await CloudStorageConfigsDAO().findOne(["total_usage"], {});
缺失 where

```typescript
const config = await CloudStorageConfigsDAO().findOne(["total_usage"], {
    user_uuid: userUUID
});
```

2021-03-17 09:49 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +    const config = await CloudStorageConfigsDAO().findOne(["total_usage"], {});
变量名应该为: cloudStorageConfig

2021-03-17 09:49 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +    if (totalUsage > 2 * 1024 * 1024 * 1024) {
这是 2M 么？最好附上注释说明。并且一般习惯把 单位计算放在前面，其他的放在后面，方便理解，如: `1024 * 1024 * 1024 * 2`

2021-03-17 09:49 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +    const totalUsage = (config ? Number(config.total_usage) : 0) + fileSize;
这里会有一个问题，假设我们在测试数据或其他原因在修改数据库的时候，我们不小心把 total_usage 改为字符串，那么就会有问题，我们可以假设 value 为: "11a"，那么这个计算表达式将为: NaN

所以这里最好改为: 

```typescript
const totalUsage = (Number(config?.total_usage) || 0) + fileSize;
```

2021-03-17 09:49 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +    if (fileUUID) {
在什么情况下，将没有 `fileUUID`?

2021-03-17 09:49 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +        const userFile = await CloudStorageUserFilesDAO().findOne([], {
这个其实不需要，我们虽然分两个表来存储数据，但是我们对这些表的操作(增、删、改) 时，都是事务性的，所有是能够保证，要么都成功，要么都失败。所以这里需要判断 `CloudStorageFilesDAO`

2021-03-17 09:49 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +    try {
这个 try 太下面了，我们应该放在 22 行，从有 await 的时候，就需要添加，以保证程序的稳定性

2021-03-17 09:49 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +        const cloudStorageFilesData = {
这个没有必要单独的赋值为一个变量，直接写在 insert 里就好。我之前其他的代码之所以有些是存放成一个变量，是因为我会对其做额外的操作，但是你这里并没有，所有可以进行删除

2021-03-17 09:49 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +            commands.push(CloudStorageFilesDAO(t).insert(cloudStorageFilesData));
如果只对一个数据库做操作(增、删、改)，那么是没有必要上 事务的，所有这里的 `transaction` 是可以删除的

2021-03-17 09:49 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +            commands.push(CloudStorageFilesDAO(t).insert(cloudStorageFilesData));
而且我记得。我们之前讨论过，这里放在 redis里，而非 mysql 里，否则会有脏数据

2021-03-17 09:49 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +        console.log(e);
console.error(err)

2021-03-17 10:01 UTC, hyrious commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +            commands.push(CloudStorageFilesDAO(t).insert(cloudStorageFilesData));
但是存数据库的话就可以实现恢复/重新上传等行为，比如重新打开应用看到上次没传完的任务。

2021-03-18 02:02 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +            commands.push(CloudStorageFilesDAO(t).insert(cloudStorageFilesData));
经过讨论，当前版本不做《断点续传》的功能，所以这里还是恢复使用 Redis 来处理，后期如果有需要，再进行讨论，选择其技术细节

2021-03-18 07:11 UTC, BlackHole1 requested changes

2021-03-18 07:11 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +        if (totalUsage > 1024 * 1024 * 1024 * 2) {
需要改成 `>=` 么？
要不要和  @Leooeloel 确认下

2021-03-18 07:11 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +            `cloudStorage:${userUUID}:${fileUUID}`,
key 的生成，需要写在 `RedisKey` 里

参看：https://github.com/netless-io/flat-server/blob/feat-cloud-storage/src/utils/Redis.ts

2021-03-18 07:11 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +            JSON.stringify({ fileName, fileSize }),
这个之前不是说在 `Finsh` 里也可以拿到 这些信息么，那这里还需要进行设置么

2021-03-18 07:11 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +                type: "number",
integer

2021-03-18 07:11 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +}
一般把 UploadStartResponse 放在文件的最下方

2021-03-18 07:11 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/Router.ts
> +    }),
既然我们的 `path` 里已经有了: `alibabaCloud`
那么这里也都改下吧:
例如: "cloud-storage/alibaba-cloud/upload/start",

2021-03-18 07:23 UTC, Cheerego7 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +        if (totalUsage > 1024 * 1024 * 1024 * 2) {
他说不需要

2021-03-18 07:26 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +        if (totalUsage > 1024 * 1024 * 1024 * 2) {
好的

2021-03-18 07:27 UTC, BlackHole1 requested changes

2021-03-18 07:27 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +                stsToken: await aliyunGetSTSToken(),
这个 token 需要保存么

2021-03-18 07:32 UTC, Cheerego7 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +            JSON.stringify({ fileName, fileSize }),
Finish 没有这些参数……

2021-03-18 07:37 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/upload/alibabaCloud/Start.ts
> +            JSON.stringify({ fileName, fileSize }),
好的

2021-03-18 07:40 UTC, BlackHole1 commented
代码里还是有很多是 aliyun，统一下，全部改成: alibabaCloud 吧

2021-03-18 08:04 UTC, BlackHole1 approved these changes

2021-03-18 08:07 UTC, merged