feat(cloud-storage): add convert start api
netless-io/flat-server pull request #284
Opened 2021-03-24 10:26 UTC by Cheerego7

2021-03-24 10:43 UTC, BlackHole1 requested changes

2021-03-24 10:43 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/Router.ts
> +        path: "cloud-storage/convert",
/convert/start

2021-03-24 10:43 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Start.ts
> +        if (fileInfo.convert_step === FileConvertStep.Converting) {
既然下面的已经封装了一个函数，那这个也封装一个吧

2021-03-24 10:43 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Start.ts
> +        const taskToken = createWhiteboardTaskToken(taskUUID);
既然数据库里已经有tasktoken了，那这里就直接用数据库的就好

2021-03-24 10:43 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Start.ts
> +        const result = await whiteboardCreateConversionTask({ resource, type: fileType });
这个和下面的mysql操作放在一起，并上 事务。不然的话这里会有一个问题，假如这里成功了，数据库操作失败了，那就会出现数据不同步的问题

2021-03-24 10:43 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Start.ts
> +        const result = await whiteboardCreateConversionTask({ resource, type: fileType });
这个和下面的mysql操作放在一起，并上 事务。不然的话这里会有一个问题，假如这里成功了，数据库操作失败了，那就会出现数据不同步的问题

2021-03-24 10:43 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Start.ts
> +        }
这里对fileInfo进行解构吧

2021-03-24 10:43 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Start.ts
> +        const resource = fileInfo.file_url;
没必要的的代码，可以在上面的解构语句中重命名，如:

```typescript
const { a:x } = y;
console.log(x);
```

2021-03-24 10:43 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Start.ts
> +                taskToken,
直接返回空对象就好，因为我们list里是有taskUUID 和 taskToken 的，所以前端是知道这些信息的

2021-03-24 10:43 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Start.ts
> +            code: ErrorCode.FileConvertFailed,
统一改成 CurrentProcessFailed吧

2021-03-24 10:43 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Start.ts
> +import { isConverted, determineType } from "./Utils";
Utils的代码是不是忘记上传了

2021-03-24 11:33 UTC, Cheerego7 commented on src/v1/controller/cloudStorage/convert/Start.ts
> +                taskToken,
当前端给我们打了convert/start 接口时，才能拿到后端签给前端的taskUUID和taskToken，难道说他们打完这个接口，得再去打一次list嘛

2021-03-25 01:07 UTC, hyrious approved these changes

2021-03-25 02:13 UTC, BlackHole1 requested changes

2021-03-25 02:13 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Start.ts
> +            const result = await whiteboardCreateConversionTask({ resource, type: fileType });
还是放在外面吧，本来我的本意是在事务里是:

// await 数据库操作
// await whiteboardCreateConversionTask

因为这样的话，即使 whiteboardCreateConversionTask 请求失败，数据库也会回滚。

但是目前看来，这样做并不行，因为 数据库操作里用到了 whiteboardCreateConversionTask 的 response，导致 数据库操作必须晚于 whiteboardCreateConversionTask 执行。

所以这里就没必要放在 transaction 里了。

虽然这里有可能出现：白板开始转换，但是数据库操作失败导致回滚，带来的数据不一致，但问题不大。

因为对白板转换来说，多次转换并不会造成什么影响

2021-03-25 02:13 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Utils.ts
> +        return "static";
这里没有特别复杂的操作，可以用三目运算符

2021-03-25 04:04 UTC, closed without merging