feat(cloud-storage): add convert finish api
netless-io/flat-server pull request #289
Opened 2021-03-25 08:27 UTC by Cheerego7

2021-03-25 11:24 UTC, hyrious approved these changes

2021-03-26 01:48 UTC, BlackHole1 requested changes

2021-03-26 01:48 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Finish.ts
> +                code: ErrorCode.FileIsConverted,
这个和上面的errorcode写反了

2021-03-26 01:48 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Finish.ts
> +                    code: ErrorCode.CurrentProcessFailed,
FileConvertFailed

2021-03-26 01:48 UTC, BlackHole1 commented on src/v1/controller/cloudStorage/convert/Finish.ts
> +                };
这里可以放在 default 里
code: convertStatus === "Waiting" ? ErrorCode.FileIsConvertWaiting : ErrorCode.FileIsConverting

2021-03-26 05:37 UTC, BlackHole1 approved these changes

2021-03-26 05:38 UTC, merged