docs(api): add docs folder
netless-io/flat-server pull request #45
Opened 2020-12-23 03:43 UTC by hyrious

2020-12-23 06:29 UTC, BlackHole1 submitted a review, later dismissed

2020-12-26 01:46 UTC, BlackHole1 requested changes

2020-12-26 01:46 UTC, BlackHole1 commented on docs/v1/README.md
> +{ title, type, beginTime, endTime, cyclical?, docs? }
cyclical 不是可选的

2020-12-26 01:46 UTC, BlackHole1 commented on docs/v1/README.md
> +    title, beginTime, endTime?, roomStatus # roomStatus: "Pending" | "Running" | "Stopped"
这个格式可以优化下，以及 `roomUUID` 和 `cyclicalUUID` 不是可选的。

其中 `cyclicalUUID` 只是有可能为空字符串

2020-12-27 14:04 UTC, hyrious commented
This branch has some merge commits which are not needed.
I will open another pr to sync making docs when your refactoring is done.

2020-12-28 00:48 UTC, closed without merging